#!/bin/bash
# audio_output
# A bash based gui to set the pulseaudio output device
# Isaac Hailperin <isaac.hailperin@gmail.com>
# 11-SEP-2015

# usage: ./audio_output

# Set your remote server here
REMOTE_PA_SERVER=foobar

# Usually the port is the default pulseaudio port
REMOTE_PA_PORT=4713
# The second options, usually local host
LOCAL_HOST=$(hostname)

# Test remote host:port availability (TCP-only as UDP does not reply)
# http://www.legroom.net/2010/05/02/port-testing-and-scanning-bash
    # $1 = hostname
    # $2 = port
function port() {
    (echo >/dev/tcp/$1/$2) &>/dev/null
    if [ $? -eq 0 ]; then
        echo "open"
    else
        echo "closed"
    fi
}

PA_SERVER=$(zenity --list --title "Please choose your sound output device" \
    --width=400 --height=150 \
    --column "Computer" --column "Amplification" \
    "${REMOTE_PA_SERVER}" "HiFi Sound System" \
    "${LOCAL_HOST}" "Local Speakers" 2>/dev/null)
if [ $? -ne 0 ]; then
    exit 0
fi

# test for open port on configured server, fall back to localhost if not open
if [ "${PA_SERVER}" == "${REMOTE_PA_SERVER}" ]; then
    remote_state=$(port ${PA_SERVER} ${REMOTE_PA_PORT})
    if [ "${remote_state}" == "closed" ];then
        PA_SERVER="${LOCAL_HOST}"
        zenity --warning --text "${REMOTE_PA_SERVER} seems not available for audio output. Maybe you should switch it on or reboot it?"
        pax11publish -r
        zenity --info --text "Meanwhile audio will be played locally." 2>/dev/null
    else
        pax11publish -e -S "${PA_SERVER}"
        zenity --info --text "Audio will now be played through ${PA_SERVER}. You might need to restart your application." 2>/dev/null
    fi
    exit 0
else
    pax11publish -r
    zenity --info --text "Audio will be played locally. You might need to restart your application." 2>/dev/null
fi

