#!/bin/bash
# call HandBrakeCLI via docker
# You will need to adjust your volume and devices attached to the container

docker container run --rm -it -v /mnt/video/new:/mnt/video/new -v /mnt/cdrom:/mnt/cdrom --device /dev/sr0 isaach/handbrakecli HandBrakeCLI "$@"
